<template>
  <div><el-page-header @back="$router.push('/admin/counselors')" title="返回"/><el-card style="margin-top:16px" v-loading="loading">
    <div class="detail-head"><div><el-avatar :size="70" :src="detail.photoUrl"><el-icon><UserFilled/></el-icon></el-avatar><div><h3>{{detail.name}}</h3><span>{{detail.username}}</span></div></div><div><el-button @click="resetPassword">重置密码</el-button><el-button type="primary" @click="openEdit">编辑资料</el-button></div></div>
    <el-descriptions :column="isMobile?1:2" border><el-descriptions-item label="性别">{{detail.gender}}</el-descriptions-item><el-descriptions-item label="学院">{{detail.college}}</el-descriptions-item><el-descriptions-item label="政治面貌">{{detail.politicalStatus}}</el-descriptions-item><el-descriptions-item label="最高学历">{{detail.highestEducation}}</el-descriptions-item><el-descriptions-item label="办公地址">{{detail.officeAddress}}</el-descriptions-item><el-descriptions-item label="电话">{{detail.phone}}</el-descriptions-item><el-descriptions-item label="邮箱">{{detail.email}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="statusType(detail.accountStatus)">{{statusLabel(detail.accountStatus)}}</el-tag></el-descriptions-item></el-descriptions>
    <h4>填报历史</h4><el-table v-if="detail.submissions?.length" :data="detail.submissions"><el-table-column prop="batchTitle" label="批次"/><el-table-column label="状态"><template #default="{row}">{{submissionStatus(row.status)}}</template></el-table-column><el-table-column prop="submittedAt" label="提交时间"/></el-table><el-empty v-else description="暂无填报记录"/>
  </el-card>
  <el-dialog v-model="visible" title="编辑辅导员资料" width="min(94%, 620px)"><el-form label-position="top"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><el-form-item label="性别"><el-select v-model="form.gender" style="width:100%"><el-option label="男" value="男"/><el-option label="女" value="女"/></el-select></el-form-item><el-form-item label="学院"><el-select v-model="form.collegeId" style="width:100%"><el-option v-for="c in colleges" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="政治面貌"><el-input v-model="form.politicalStatus"/></el-form-item><el-form-item label="最高学历"><el-input v-model="form.highestEducation"/></el-form-item><el-form-item label="办公地址"><el-input v-model="form.officeAddress"/></el-form-item><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="账号状态"><el-radio-group v-model="form.accountStatus"><el-radio-button value="ACTIVE">启用</el-radio-button><el-radio-button value="DISABLED">禁用</el-radio-button></el-radio-group></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save" :loading="saving">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{ref,reactive,computed,onMounted}from'vue';import{useRoute}from'vue-router';import{ElMessage,ElMessageBox}from'element-plus';import api from'../../utils/request';const route=useRoute(),detail=ref({}),colleges=ref([]),visible=ref(false),loading=ref(false),saving=ref(false),form=reactive({});const isMobile=computed(()=>window.innerWidth<768);async function load(){loading.value=true;try{const[d,c]=await Promise.all([api.get('/admin/counselors/'+route.params.id),api.get('/public/colleges')]);detail.value=d.data;colleges.value=c.data}finally{loading.value=false}}onMounted(load);function openEdit(){Object.assign(form,{name:detail.value.name,gender:detail.value.gender,collegeId:detail.value.collegeId,politicalStatus:detail.value.politicalStatus,highestEducation:detail.value.highestEducation,officeAddress:detail.value.officeAddress,phone:detail.value.phone,email:detail.value.email,accountStatus:detail.value.accountStatus});visible.value=true}async function save(){saving.value=true;try{await api.put('/admin/counselors/'+route.params.id,form);ElMessage.success('资料修改成功');visible.value=false;load()}finally{saving.value=false}}async function resetPassword(){await ElMessageBox.confirm('重置后原密码立即失效，确认继续吗？','重置密码',{type:'warning'});const{data}=await api.post('/admin/counselors/'+route.params.id+'/reset-password');await ElMessageBox.alert('临时密码：'+data.temporaryPassword+'\n该密码仅显示一次，请安全交给辅导员。','密码重置成功',{confirmButtonText:'我已记录'})}function statusType(v){return v==='ACTIVE'?'success':v==='DISABLED'?'danger':'warning'}function statusLabel(v){return({ACTIVE:'已启用',DISABLED:'已禁用',PENDING_REVIEW:'待审核',REJECTED:'已驳回'})[v]||v}function submissionStatus(v){return({DRAFT:'草稿',SUBMITTED:'已提交',APPROVED:'已通过',REJECTED:'已驳回'})[v]||v}
</script>
<style scoped>.detail-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.detail-head>div{display:flex;align-items:center;gap:14px}.detail-head h3{margin:0 0 5px}.detail-head span{color:#909399}.el-card h4{margin-top:22px}</style>
