<template>
  <div class="alerts-page">
    <div class="page-title"><div><h2>心理风险预警</h2><p>仅展示需要人工关怀的较高风险和高风险人员</p></div><el-button @click="load"><el-icon><Refresh /></el-icon>刷新</el-button></div>
    <el-alert title="请严格保护心理健康隐私，预警信息不得用于绩效考核、晋升或纪律处理。" type="warning" show-icon :closable="false"/>
    <el-empty v-if="!alerts.length" description="当前没有风险预警"/>
    <div class="alert-list"><el-card v-for="item in alerts" :key="item.id" class="alert-card"><div class="person"><el-avatar :size="50" :src="item.photoUrl"/><div><strong>{{item.name}}</strong><span>{{item.collegeName}}</span></div></div><div class="risk"><el-tag :type="item.riskLevel==='HIGH'?'danger':'warning'">{{riskLabel(item.riskLevel)}}</el-tag><p>{{item.reason}}</p></div><div class="status"><span>{{statusLabel(item.status)}}</span><small>{{format(item.createdAt)}}</small></div><el-button type="primary" plain @click="open(item)">跟进处理</el-button></el-card></div>
    <el-dialog v-model="visible" title="心理风险跟进" width="min(94%, 620px)"><div v-if="current" class="dialog-person"><el-avatar :size="46" :src="current.photoUrl"/><div><strong>{{current.name}}</strong><p>{{current.collegeName}} · {{riskLabel(current.riskLevel)}}</p></div></div><el-alert v-if="current" :title="current.reason" type="error" :closable="false" show-icon/><el-form label-position="top" style="margin-top:16px"><el-form-item label="处理状态"><el-radio-group v-model="form.status"><el-radio-button value="PENDING">待处理</el-radio-button><el-radio-button value="PROCESSING">处理中</el-radio-button><el-radio-button value="COMPLETED">已完成</el-radio-button></el-radio-group></el-form-item><el-form-item label="联系时间"><el-date-picker v-model="form.contactedAt" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="跟进说明"><el-input v-model="form.followUpNote" type="textarea" :rows="5" placeholder="记录联系和关怀情况，不要填写与跟进无关的敏感信息"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存跟进记录</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{ref,reactive,onMounted}from'vue';import{ElMessage}from'element-plus';import api from'../../utils/request';const alerts=ref([]),visible=ref(false),current=ref(null),form=reactive({status:'PENDING',contactedAt:null,followUpNote:''});async function load(){alerts.value=(await api.get('/admin/psych/alerts')).data}onMounted(load);function open(item){current.value=item;Object.assign(form,{status:item.status,contactedAt:item.contactedAt,followUpNote:item.followUpNote||''});visible.value=true}async function save(){await api.put(`/admin/psych/alerts/${current.value.id}`,form);ElMessage.success('跟进记录已保存');visible.value=false;load()}function riskLabel(v){return v==='HIGH'?'高风险':'较高风险'}function statusLabel(v){return({PENDING:'待处理',PROCESSING:'处理中',COMPLETED:'已完成'})[v]}function format(v){return v?String(v).replace('T',' ').slice(0,16):''}
</script>
<style scoped>
.page-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.page-title h2{margin:0 0 5px}.page-title p{margin:0;color:#667085}.alert-list{margin-top:16px;display:grid;gap:12px}.alert-card :deep(.el-card__body){display:grid;grid-template-columns:220px 1fr 120px 100px;align-items:center;gap:18px}.person,.dialog-person{display:flex;align-items:center;gap:12px}.person strong,.person span{display:block}.person span,.status small,.dialog-person p{color:#667085;font-size:12px;margin-top:4px}.risk p{margin:7px 0;color:#475467}.status span,.status small{display:block}.dialog-person{margin-bottom:14px}.dialog-person p{margin:3px 0}@media(max-width:850px){.alert-card :deep(.el-card__body){grid-template-columns:1fr 90px}.risk{grid-column:1/-1}.status{grid-column:1}.alert-card .el-button{grid-column:2}}@media(max-width:480px){.page-title p{display:none}.alert-card :deep(.el-card__body){display:flex;flex-direction:column;align-items:stretch;gap:12px}.alert-card .el-button{width:100%}}
</style>
