<template>
  <div class="admin-page">
    <div class="page-title"><div><h2>心理评估批次</h2><p>发布和管理辅导员心理健康自评任务</p></div><el-button type="primary" @click="openCreate"><el-icon><Plus /></el-icon>新建批次</el-button></div>
    <el-table :data="batches" border class="desktop-table">
      <el-table-column prop="title" label="批次名称" min-width="180"/><el-table-column prop="startTime" label="开始时间" width="170"/><el-table-column prop="endTime" label="结束时间" width="170"/>
      <el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="statusType(row.status)">{{ statusLabel(row.status) }}</el-tag></template></el-table-column>
      <el-table-column label="操作" width="210"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" text type="primary" @click="edit(row)">编辑</el-button><el-button v-if="row.status==='DRAFT'" text type="success" @click="changeStatus(row,'PUBLISHED')">发布</el-button><el-button v-if="row.status==='PUBLISHED'" text type="danger" @click="changeStatus(row,'ENDED')">结束</el-button></template></el-table-column>
    </el-table>
    <div class="mobile-cards"><el-card v-for="row in batches" :key="row.id"><div class="card-line"><strong>{{row.title}}</strong><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></div><p>{{row.description}}</p><div class="time">{{format(row.startTime)}} 至 {{format(row.endTime)}}</div><div class="card-actions"><el-button v-if="row.status==='DRAFT'" @click="edit(row)">编辑</el-button><el-button v-if="row.status==='DRAFT'" type="primary" @click="changeStatus(row,'PUBLISHED')">发布</el-button><el-button v-if="row.status==='PUBLISHED'" type="danger" @click="changeStatus(row,'ENDED')">结束</el-button></div></el-card></div>
    <el-dialog v-model="visible" :title="form.id?'编辑心理评估批次':'新建心理评估批次'" width="min(92%, 600px)"><el-form label-position="top"><el-form-item label="批次名称"><el-input v-model="form.title"/></el-form-item><el-form-item label="批次说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="评估时间"><el-date-picker v-model="timeRange" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{ref,reactive,onMounted}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import api from'../../utils/request';const batches=ref([]),visible=ref(false),timeRange=ref([]),form=reactive({id:null,title:'',description:''});async function load(){batches.value=(await api.get('/admin/psych/batches')).data}onMounted(load);function openCreate(){Object.assign(form,{id:null,title:'',description:''});timeRange.value=[];visible.value=true}function edit(row){Object.assign(form,{id:row.id,title:row.title,description:row.description});timeRange.value=[row.startTime,row.endTime];visible.value=true}async function save(){if(!form.title)return ElMessage.warning('请输入批次名称');const body={title:form.title,description:form.description,startTime:timeRange.value?.[0],endTime:timeRange.value?.[1],anonymousStatistics:true};form.id?await api.put(`/admin/psych/batches/${form.id}`,body):await api.post('/admin/psych/batches',body);visible.value=false;ElMessage.success('保存成功');load()}async function changeStatus(row,status){await ElMessageBox.confirm(status==='PUBLISHED'?'发布后辅导员即可参加评估，确认发布吗？':'结束后不能再次开放，确认结束吗？','确认操作',{type:'warning'});await api.put(`/admin/psych/batches/${row.id}/status`,null,{params:{status}});ElMessage.success('操作成功');load()}function statusLabel(v){return({DRAFT:'草稿',PUBLISHED:'进行中',ENDED:'已结束'})[v]}function statusType(v){return({DRAFT:'info',PUBLISHED:'success',ENDED:''})[v]}function format(v){return v?String(v).replace('T',' ').slice(0,16):'不限'}
</script>
<style scoped>
.page-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-title h2{margin:0 0 5px}.page-title p,.time{color:#667085;font-size:13px;margin:0}.mobile-cards{display:none}.card-line{display:flex;justify-content:space-between;gap:10px}.card-actions{margin-top:14px;display:flex}.mobile-cards .el-card{margin-bottom:10px}@media(max-width:767px){.desktop-table{display:none}.mobile-cards{display:block}.page-title h2{font-size:20px}.page-title p{display:none}}
</style>
