<template>
  <div class="batch-fill" v-loading="loading">
    <el-page-header @back="$router.push('/')" title="返回"><template #content><h3>{{ submissionId ? '编辑信息填报' : '信息填报' }}</h3></template></el-page-header>
    <el-alert v-if="reviewComment" :title="'上次驳回原因：' + reviewComment" type="warning" show-icon :closable="false" style="margin-top:16px" />
    <el-card style="margin-top:16px"><el-form :model="form" label-width="100px">
      <h4>基本信息</h4>
      <el-form-item label="姓名"><el-input v-model="form.name" /></el-form-item>
      <el-form-item label="性别"><el-select v-model="form.gender"><el-option label="男" value="男"/><el-option label="女" value="女"/></el-select></el-form-item>
      <el-form-item label="学院"><el-select v-model="form.collegeId" style="width:100%"><el-option v-for="c in colleges" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item>
      <el-form-item label="政治面貌"><el-select v-model="form.politicalStatus" style="width:100%"><el-option v-for="p in politicalStatuses" :key="p" :label="p" :value="p"/></el-select></el-form-item>
      <el-form-item label="最高学历"><el-select v-model="form.highestEducation" style="width:100%"><el-option v-for="e in educations" :key="e" :label="e" :value="e"/></el-select></el-form-item>
      <el-form-item label="办公地址"><el-input v-model="form.officeAddress"/></el-form-item><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="照片"><PhotoUpload v-model="form.photoUrl"/></el-form-item>
      <h4>工作经历 <el-button type="primary" text @click="addWork">添加</el-button></h4>
      <div v-for="(w,i) in form.workExperiences" :key="'w'+i" class="exp-item"><el-row :gutter="12"><el-col :xs="24" :sm="12"><el-form-item label="单位"><el-input v-model="w.organization"/></el-form-item></el-col><el-col :xs="24" :sm="12"><el-form-item label="职位"><el-input v-model="w.position"/></el-form-item></el-col></el-row><el-row :gutter="12"><el-col :xs="24" :sm="10"><el-form-item label="开始"><el-date-picker v-model="w.startDate" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :xs="24" :sm="10"><el-form-item label="结束"><el-date-picker v-model="w.endDate" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :xs="24" :sm="4"><el-button type="danger" text @click="form.workExperiences.splice(i,1)">删除</el-button></el-col></el-row><el-form-item label="描述"><el-input v-model="w.description" type="textarea"/></el-form-item></div>
      <h4>教育经历 <el-button type="primary" text @click="addEducation">添加</el-button></h4>
      <div v-for="(e,i) in form.educationExperiences" :key="'e'+i" class="exp-item"><el-row :gutter="12"><el-col :xs="24" :sm="12"><el-form-item label="学校"><el-input v-model="e.school"/></el-form-item></el-col><el-col :xs="24" :sm="12"><el-form-item label="专业"><el-input v-model="e.major"/></el-form-item></el-col></el-row><el-row :gutter="12"><el-col :xs="24" :sm="8"><el-form-item label="学位"><el-input v-model="e.degree"/></el-form-item></el-col><el-col :xs="24" :sm="8"><el-form-item label="开始"><el-date-picker v-model="e.startDate" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :xs="24" :sm="8"><el-form-item label="结束"><el-date-picker v-model="e.endDate" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col></el-row><el-button type="danger" text @click="form.educationExperiences.splice(i,1)">删除</el-button></div>
      <div class="actions"><el-button @click="saveDraft" :loading="saving">保存草稿</el-button><el-button type="primary" @click="submitForm" :loading="submitting">提交信息</el-button></div>
    </el-form></el-card>
  </div>
</template>
<script setup>
import{reactive,ref,onMounted}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage,ElMessageBox}from'element-plus';import api from'../../utils/request';import PhotoUpload from'../../components/PhotoUpload.vue'
const route=useRoute(),router=useRouter(),loading=ref(true),saving=ref(false),submitting=ref(false),colleges=ref([]),submissionId=ref(route.query.submissionId?Number(route.query.submissionId):null),reviewComment=ref('');const politicalStatuses=['中共党员','中共预备党员','共青团员','群众','民主党派'],educations=['博士','硕士','本科','大专'];const form=reactive({name:'',gender:'',collegeId:null,politicalStatus:'',highestEducation:'',officeAddress:'',phone:'',email:'',photoUrl:'',workExperiences:[],educationExperiences:[]})
function applyData(d){Object.assign(form,{name:d.name||'',gender:d.gender||'',collegeId:d.collegeId||null,politicalStatus:d.politicalStatus||'',highestEducation:d.highestEducation||'',officeAddress:d.officeAddress||'',phone:d.phone||'',email:d.email||'',photoUrl:d.photoUrl||'',workExperiences:(d.workExperiences||[]).map(x=>({...x})),educationExperiences:(d.educationExperiences||[]).map(x=>({...x}))});reviewComment.value=d.reviewComment||''}
onMounted(async()=>{try{colleges.value=(await api.get('/public/colleges')).data;if(submissionId.value){const d=(await api.get(`/counselor/submissions/${submissionId.value}`)).data;if(String(d.batchId)!==String(route.params.id))throw new Error('记录与批次不匹配');applyData(d)}else applyData((await api.get('/counselor/profile')).data)}finally{loading.value=false}})
function addWork(){form.workExperiences.push({organization:'',position:'',startDate:'',endDate:'',description:''})}function addEducation(){form.educationExperiences.push({school:'',major:'',degree:'',startDate:'',endDate:''})}
async function persist(){const r=submissionId.value?await api.put(`/counselor/submissions/${submissionId.value}`,form):await api.post(`/counselor/submissions?batchId=${route.params.id}`,form);submissionId.value=r.data.id}
async function saveDraft(){saving.value=true;try{await persist();ElMessage.success('草稿已保存');router.replace(`/batch/${route.params.id}/fill?submissionId=${submissionId.value}`)}finally{saving.value=false}}
async function submitForm(){await ElMessageBox.confirm('确认提交本次信息吗？','确认',{type:'warning'});submitting.value=true;try{await persist();await api.post(`/counselor/submissions/${submissionId.value}/submit`);ElMessage.success('提交成功');router.push('/')}finally{submitting.value=false}}
</script>
<style scoped>.batch-fill{max-width:1000px;margin:auto}.batch-fill h4{margin:20px 0 12px}.exp-item{background:#f5f7fa;padding:12px;border-radius:6px;margin-bottom:12px}.actions{margin-top:24px;text-align:center}.actions .el-button{min-width:110px}@media(max-width:767px){.batch-fill :deep(.el-form-item__label){width:82px!important}.batch-fill :deep(.el-form-item__content){margin-left:82px!important}}</style>
